New log file opened at Mon Oct 26 01:16:49 HKT 2015 by 32066@BeenoTung-Archlinux-Home
Taking next connection to: 42879
New client attempting to connect on port: 34800-42879
  Address = /192.168.1.3:42879
This client on port 34800 has uuid b6a83db0-8785-48df-8a2c-62426aed173f configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-b6a83db0-8785-48df-8a2c-62426aed173f
Taking next connection to: 42879
New client attempting to connect on port: 34802-42879
  Address = /192.168.1.3:42879
Handshake exception on socket: 34802
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 42879
New client attempting to connect on port: 34804-42879
  Address = /192.168.1.3:42879
This client on port 34804 has uuid 76b06135-b610-4a0e-ac60-39e7bf032341 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-b6a83db0-8785-48df-8a2c-62426aed173f, activator-76b06135-b610-4a0e-ac60-39e7bf032341
Taking next connection to: 42879
